### PR TITLE
Afiune/make it a cookbook

### PR DESCRIPTION
**Pull request by afiune**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by seth** [comment]
@delivery approve

**Comment by seth** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: e0d06b07-c64b-4194-ab1f-91e9ab982d57 approved by: @seth

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by seth** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: e0d06b07-c64b-4194-ab1f-91e9ab982d57 delivered by: @seth

**Pull request merged**
